#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="${ENV_FILE:-${ROOT_DIR}/.env.production}"
VPS_EXPOSURE_PROFILE="${VPS_EXPOSURE_PROFILE:-smoke}"

random_base64() {
  openssl rand -base64 48 | tr -d '\n'
}

random_hex() {
  openssl rand -hex 24 | tr -d '\n'
}

is_ipv4() {
  [[ "$1" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]
}

resolve_domain() {
  if [[ -n "${APP_DOMAIN:-}" ]]; then
    printf '%s\n' "${APP_DOMAIN}"
    return 0
  fi

  local ip="${VPS_PUBLIC_IP:-${VPS_HOST:-}}"
  if [[ -z "${ip}" ]]; then
    echo "Set APP_DOMAIN=seudominio.com or VPS_PUBLIC_IP=IP_DA_VPS." >&2
    exit 1
  fi
  if ! is_ipv4 "${ip}"; then
    echo "VPS_PUBLIC_IP/VPS_HOST must be an IPv4 address when APP_DOMAIN is not set." >&2
    exit 1
  fi
  printf '%s.sslip.io\n' "${ip}"
}

require_external() {
  local key="$1"
  local value="${!key:-}"
  if [[ -z "${value}" ]]; then
    echo "${key} is required when VPS_EXPOSURE_PROFILE=production." >&2
    exit 1
  fi
}

case "${VPS_EXPOSURE_PROFILE}" in
  smoke|production) ;;
  *)
    echo "Invalid VPS_EXPOSURE_PROFILE=${VPS_EXPOSURE_PROFILE}. Use smoke or production." >&2
    exit 1
    ;;
esac

app_domain="$(resolve_domain)"
build_sha="$(git -C "${ROOT_DIR}" rev-parse --short=12 HEAD 2>/dev/null || echo vps-manual)"

email_verification_required="${EMAIL_VERIFICATION_REQUIRED:-true}"
turnstile_required="${TURNSTILE_REQUIRED:-true}"
next_public_turnstile_site_key="${NEXT_PUBLIC_TURNSTILE_SITE_KEY:-}"

if [[ "${VPS_EXPOSURE_PROFILE}" == "smoke" ]]; then
  email_verification_required="${EMAIL_VERIFICATION_REQUIRED:-false}"
  turnstile_required="${TURNSTILE_REQUIRED:-false}"
  next_public_turnstile_site_key="${NEXT_PUBLIC_TURNSTILE_SITE_KEY:-disabled}"
else
  require_external MERCADO_PAGO_ACCESS_TOKEN
  require_external MERCADO_PAGO_WEBHOOK_SECRET
  require_external RESEND_API_KEY
  require_external TURNSTILE_SECRET_KEY
  require_external NEXT_PUBLIC_TURNSTILE_SITE_KEY
fi

llm_api_key="${LLM_API_KEY:-${OPENROUTER_API_KEY:-}}"
if [[ -n "${llm_api_key}" ]]; then
  llm_provider="${LLM_PROVIDER:-openrouter}"
else
  llm_provider="${LLM_PROVIDER:-none}"
fi

umask 077
tmp_file="$(mktemp)"
{
  printf '# Generated by scripts/vps/generate-web-env.sh. Do not commit this file.\n'
  printf 'APP_DOMAIN=%s\n' "${app_domain}"
  printf 'CADDY_EMAIL=%s\n' "${CADDY_EMAIL:-admin@${app_domain}}"
  printf 'PUBLIC_APP_URL=https://%s\n' "${app_domain}"
  printf 'PUBLIC_API_URL=https://api.%s\n' "${app_domain}"
  printf 'CORS_ORIGIN=https://%s\n' "${app_domain}"
  printf 'CORS_ORIGINS=https://%s\n' "${app_domain}"
  printf 'S3_PUBLIC_ENDPOINT=https://storage.%s\n' "${app_domain}"
  printf 'S3_CORS_ALLOWED_ORIGINS_JSON=%s\n' "'[\"https://${app_domain}\"]'"
  printf '\n'
  printf 'VPS_PROVIDER=%s\n' "${VPS_PROVIDER:-digitalocean}"
  printf 'VPS_SIZE_PROFILE=%s\n' "${VPS_SIZE_PROFILE:-budget}"
  printf 'VPS_DATA_DIR=%s\n' "${VPS_DATA_DIR:-/srv/clipbr/data}"
  printf 'VPS_BACKUP_DIR=%s\n' "${VPS_BACKUP_DIR:-/srv/clipbr/backups}"
  printf '\n'
  printf 'NODE_ENV=production\n'
  printf 'APP_ENV=production\n'
  printf 'LOG_LEVEL=%s\n' "${LOG_LEVEL:-info}"
  printf 'BUILD_SHA=%s\n' "${BUILD_SHA:-${build_sha}}"
  printf 'RATE_LIMIT_MAX=%s\n' "${RATE_LIMIT_MAX:-300}"
  printf 'TERMS_VERSION=%s\n' "${TERMS_VERSION:-terms-2026-06}"
  printf 'PRIVACY_VERSION=%s\n' "${PRIVACY_VERSION:-privacy-2026-06}"
  printf 'JWT_ACCESS_TTL=%s\n' "${JWT_ACCESS_TTL:-15m}"
  printf 'JWT_REFRESH_DAYS=%s\n' "${JWT_REFRESH_DAYS:-30}"
  printf '\n'
  printf 'POSTGRES_DB=%s\n' "${POSTGRES_DB:-clipbr}"
  printf 'POSTGRES_USER=%s\n' "${POSTGRES_USER:-clipbr}"
  printf 'POSTGRES_PASSWORD=%s\n' "${POSTGRES_PASSWORD:-$(random_base64)}"
  printf 'POSTGRES_LOCAL_PORT=%s\n' "${POSTGRES_LOCAL_PORT:-55432}"
  printf '\n'
  printf 'REDIS_PASSWORD=%s\n' "${REDIS_PASSWORD:-$(random_base64)}"
  printf 'QUEUE_PREFIX=%s\n' "${QUEUE_PREFIX:-clipbr-vps}"
  printf 'OUTBOX_POLL_INTERVAL_MS=%s\n' "${OUTBOX_POLL_INTERVAL_MS:-1000}"
  printf 'OUTBOX_BATCH_SIZE=%s\n' "${OUTBOX_BATCH_SIZE:-20}"
  printf '\n'
  printf 'S3_REGION=%s\n' "${S3_REGION:-us-east-1}"
  printf 'S3_BUCKET=%s\n' "${S3_BUCKET:-clipbr-videos}"
  printf 'S3_ACCESS_KEY_ID=%s\n' "${S3_ACCESS_KEY_ID:-clipbr$(random_hex)}"
  printf 'S3_SECRET_ACCESS_KEY=%s\n' "${S3_SECRET_ACCESS_KEY:-$(random_base64)}"
  printf 'S3_FORCE_PATH_STYLE=true\n'
  printf '\n'
  printf 'UPLOAD_MODE=direct\n'
  printf 'MAX_UPLOAD_SIZE_BYTES=%s\n' "${MAX_UPLOAD_SIZE_BYTES:-5368709120}"
  printf 'UPLOAD_PART_SIZE_BYTES=%s\n' "${UPLOAD_PART_SIZE_BYTES:-67108864}"
  printf 'UPLOAD_QUEUE_SIZE=%s\n' "${UPLOAD_QUEUE_SIZE:-2}"
  printf 'UPLOAD_ALLOWED_MIME_TYPES=%s\n' "${UPLOAD_ALLOWED_MIME_TYPES:-video/mp4,video/quicktime,video/webm,video/x-matroska,video/x-msvideo}"
  printf '\n'
  printf 'JWT_SECRET=%s\n' "${JWT_SECRET:-$(random_base64)}"
  printf 'REFRESH_TOKEN_SECRET=%s\n' "${REFRESH_TOKEN_SECRET:-$(random_base64)}"
  printf 'MEDIA_WORKER_TOKEN=%s\n' "${MEDIA_WORKER_TOKEN:-$(random_base64)}"
  printf '\n'
  printf 'MEDIA_WORKER_TIMEOUT_MS=%s\n' "${MEDIA_WORKER_TIMEOUT_MS:-7200000}"
  printf 'MEDIA_MAX_CONCURRENT_JOBS=1\n'
  printf 'ENABLE_AI=true\n'
  printf 'ENABLE_WHISPERX=true\n'
  printf 'ENABLE_OPENCV=true\n'
  printf 'ENABLE_MEDIAPIPE=true\n'
  printf 'ENABLE_YOLO=true\n'
  printf 'MEDIA_DIARIZATION_ENABLED=false\n'
  printf 'MEDIA_TRANSCRIPTION_BATCH_SIZE=1\n'
  printf 'LLM_PROVIDER=%s\n' "${llm_provider}"
  printf 'LLM_API_KEY=%s\n' "${llm_api_key}"
  printf 'LLM_MODEL=%s\n' "${LLM_MODEL:-openai/gpt-4o-mini}"
  printf 'LLM_TIMEOUT_SECONDS=%s\n' "${LLM_TIMEOUT_SECONDS:-45}"
  printf 'WHISPERX_MODEL=tiny\n'
  printf 'WHISPERX_DEVICE=cpu\n'
  printf 'WHISPERX_COMPUTE_TYPE=int8\n'
  printf 'HF_TOKEN=%s\n' "${HF_TOKEN:-}"
  printf '\n'
  printf 'MERCADO_PAGO_ACCESS_TOKEN=%s\n' "${MERCADO_PAGO_ACCESS_TOKEN:-}"
  printf 'MERCADO_PAGO_WEBHOOK_SECRET=%s\n' "${MERCADO_PAGO_WEBHOOK_SECRET:-}"
  printf 'RESEND_API_KEY=%s\n' "${RESEND_API_KEY:-}"
  printf 'EMAIL_FROM=%s\n' "${EMAIL_FROM:-noreply@${app_domain}}"
  printf 'EMAIL_VERIFICATION_REQUIRED=%s\n' "${email_verification_required}"
  printf 'TURNSTILE_REQUIRED=%s\n' "${turnstile_required}"
  printf 'TURNSTILE_SECRET_KEY=%s\n' "${TURNSTILE_SECRET_KEY:-}"
  printf 'TURNSTILE_BYPASS_TOKEN=\n'
  printf 'ALLOW_TURNSTILE_BYPASS_IN_PRODUCTION=false\n'
  printf 'NEXT_PUBLIC_TURNSTILE_SITE_KEY=%s\n' "${next_public_turnstile_site_key}"
  printf '\n'
  printf 'OTEL_EXPORTER_OTLP_ENDPOINT=%s\n' "${OTEL_EXPORTER_OTLP_ENDPOINT:-}"
  printf 'OTEL_SERVICE_NAME=clipbr-api\n'
  printf 'VPS_BACKUP_GPG_RECIPIENT=%s\n' "${VPS_BACKUP_GPG_RECIPIENT:-}"
} > "${tmp_file}"

mv "${tmp_file}" "${ENV_FILE}"
chmod 600 "${ENV_FILE}"

echo "Generated ${ENV_FILE}"
echo "APP_DOMAIN=${app_domain}"
echo "PUBLIC_APP_URL=https://${app_domain}"
echo "PUBLIC_API_URL=https://api.${app_domain}"
echo "S3_PUBLIC_ENDPOINT=https://storage.${app_domain}"
echo "Profile=${VPS_EXPOSURE_PROFILE}"
