'use client';

import { FolderKanban, LoaderCircle, Plus, Search } from 'lucide-react';
import { FormEvent, useMemo, useState } from 'react';
import { ProjectCard } from '@/components/project-card';
import { Alert, Button, EmptyState, Input, Label, Modal, PageHeader, Skeleton, Textarea } from '@/components/ui';
import { useCollection } from '@/hooks/use-resource';
import { api, endpoints, unwrap } from '@/lib/api';
import type { Project } from '@/lib/types';

export default function ProjectsPage() {
  const { data, loading, error, refresh, setData } = useCollection<Project>(endpoints.projects); const [query, setQuery] = useState(''); const [open, setOpen] = useState(false); const [form, setForm] = useState({ name: '', description: '' }); const [busy, setBusy] = useState(false); const [formError, setFormError] = useState('');
  const projects = useMemo(() => data.filter((project) => !query || project.name.toLowerCase().includes(query.toLowerCase())), [data, query]);
  async function create(event: FormEvent) { event.preventDefault(); setBusy(true); setFormError(''); try { const project = unwrap(await api<Project | {data:Project}>(endpoints.projects, { method: 'POST', body: JSON.stringify(form) })); setData((current) => [project, ...current]); setOpen(false); setForm({ name: '', description: '' }); } catch (reason) { setFormError(reason instanceof Error ? reason.message : 'Não foi possível criar o projeto.'); } finally { setBusy(false); } }
  return <><PageHeader eyebrow="Organização" title="Projetos" description="Agrupe vídeos, cortes e exportações por campanha ou cliente." action={<Button onClick={() => setOpen(true)}><Plus className="size-4"/>Novo projeto</Button>}/>{data.length > 0 && <div className="relative mb-5 max-w-md"><Search className="absolute left-3.5 top-3.5 size-4 text-zinc-600"/><Input value={query} onChange={(event) => setQuery(event.target.value)} className="pl-10" placeholder="Buscar projetos…"/></div>}{error && <Alert>{error} <button onClick={() => void refresh()} className="underline">Tentar novamente</button></Alert>}{loading ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">{Array.from({length:8},(_,i)=><Skeleton key={i} className="h-60"/>)}</div> : projects.length ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">{projects.map((project)=><ProjectCard key={project.id} project={project}/>)}</div> : <EmptyState icon={FolderKanban} title={data.length ? 'Nenhum projeto encontrado' : 'Organize sua produção'} description={data.length ? 'Tente buscar por outro nome.' : 'Crie um projeto para reunir os vídeos e cortes de uma campanha.'} action={!data.length && <Button size="sm" onClick={() => setOpen(true)}>Criar projeto</Button>}/>}<Modal open={open} onClose={() => setOpen(false)} title="Novo projeto" description="Dê um nome que sua equipe reconheça facilmente."><form onSubmit={create} className="space-y-4">{formError && <Alert>{formError}</Alert>}<div><Label htmlFor="project-name">Nome</Label><Input id="project-name" autoFocus required minLength={2} maxLength={100} value={form.name} onChange={(event)=>setForm({...form,name:event.target.value})}/></div><div><Label htmlFor="project-description">Descrição</Label><Textarea id="project-description" maxLength={500} value={form.description} onChange={(event)=>setForm({...form,description:event.target.value})}/></div><div className="flex justify-end gap-3 pt-2"><Button type="button" variant="ghost" onClick={()=>setOpen(false)}>Cancelar</Button><Button disabled={busy}>{busy && <LoaderCircle className="size-4 animate-spin"/>}Criar projeto</Button></div></form></Modal></>;
}
