'use client';

import { Activity, Clock3, Coins, Download, Gauge, Video } from 'lucide-react';
import { ActivityChart } from '@/components/activity-chart';
import { Alert, Card, MetricCard, PageHeader, Skeleton } from '@/components/ui';
import { useResource } from '@/hooks/use-resource';
import { endpoints } from '@/lib/api';
import type { Analytics } from '@/lib/types';
import { formatDuration } from '@/lib/utils';

export default function AnalyticsPage(){
  const {data,loading,error,refresh}=useResource<Analytics>(`${endpoints.analytics}?period=30d`); const currency=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
  const health = [{label:'Tempo médio',value:formatDuration(data?.averageProcessingSeconds),Icon:Activity},{label:'Créditos usados',value:`${data?.creditsUsed??0} / ${data?.creditsLimit??0}`,Icon:Coins},{label:'Cortes gerados',value:data?.clipsGenerated??0,Icon:Video}];
  return <><PageHeader eyebrow="Performance" title="Analytics" description="Entenda o volume, o uso e a eficiência da sua operação nos últimos 30 dias."/>{error&&<div className="mb-5"><Alert>{error} <button className="underline" onClick={()=>void refresh()}>Tentar novamente</button></Alert></div>}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{loading?Array.from({length:5},(_,i)=><Skeleton key={i} className="h-32"/>):<><MetricCard label="Processamentos" value={data?.videosProcessed??0} icon={Video}/><MetricCard label="Downloads" value={data?.downloads??0} icon={Download}/><MetricCard label="Tempo usado" value={`${data?.processingMinutes??0} min`} icon={Clock3}/><MetricCard label="Custo estimado" value={currency.format(data?.totalCost??0)} icon={Coins}/><MetricCard label="Taxa de sucesso" value={`${(data?.successRate??0).toLocaleString('pt-BR',{maximumFractionDigits:1})}%`} icon={Gauge}/></>}</div><div className="mt-6 grid gap-6 xl:grid-cols-[1.55fr_.75fr]"><Card className="p-5 sm:p-6"><div><h2 className="font-semibold text-white">Processamentos e uso</h2><p className="mt-1 text-xs text-zinc-600">Volume diário no período selecionado</p></div><div className="mt-6">{loading?<Skeleton className="h-60"/>:<ActivityChart points={data?.activity}/>}</div></Card><Card className="p-5 sm:p-6"><h2 className="font-semibold text-white">Saúde da operação</h2><div className="mt-6 grid grid-cols-2 gap-3 xl:grid-cols-1">{health.map(({label,value,Icon})=><div key={label} className="rounded-xl border border-white/[.06] bg-white/[.025] p-4"><div className="flex items-center gap-2 text-xs text-zinc-600"><Icon className="size-3.5"/>{label}</div><p className="mt-2 text-lg font-bold text-white">{value}</p></div>)}</div></Card></div>{data?.byStatus?.length?<Card className="mt-6 p-5 sm:p-6"><h2 className="font-semibold text-white">Processamentos por status</h2><div className="mt-5 space-y-4">{data.byStatus.map(item=>{const total=data.byStatus!.reduce((sum,current)=>sum+current.value,0);const percent=total?item.value/total*100:0;return <div key={item.status}><div className="mb-2 flex justify-between text-xs"><span className="text-zinc-400">{item.status}</span><span className="text-zinc-600">{item.value} · {Math.round(percent)}%</span></div><div className="h-2 overflow-hidden rounded-full bg-white/[.05]"><div className="h-full rounded-full bg-lime" style={{width:`${percent}%`}}/></div></div>;})}</div></Card>:null}</>;
}
